// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOP9dmJ-mAgEBs9XQmZe2aisgVicGZvWE',
    appId: '1:677074689591:web:eb84b9fab04faeb25da9b2',
    messagingSenderId: '677074689591',
    projectId: 'fir-chat-app-4663a',
    authDomain: 'fir-chat-app-4663a.firebaseapp.com',
    storageBucket: 'fir-chat-app-4663a.appspot.com',
    measurementId: 'G-63NG89D41W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtbl-C00Esyv4NpwKJn0044gnFbg6dsmY',
    appId: '1:677074689591:android:9666712e3dcc0c205da9b2',
    messagingSenderId: '677074689591',
    projectId: 'fir-chat-app-4663a',
    storageBucket: 'fir-chat-app-4663a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeJmNQVkT9JA2hH8yWWI1FAvTsZ-07Zf8',
    appId: '1:677074689591:ios:cca417fa8ab7415c5da9b2',
    messagingSenderId: '677074689591',
    projectId: 'fir-chat-app-4663a',
    storageBucket: 'fir-chat-app-4663a.appspot.com',
    iosBundleId: 'com.chatapp.firebaseChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeJmNQVkT9JA2hH8yWWI1FAvTsZ-07Zf8',
    appId: '1:677074689591:ios:f96b358c2ee4785d5da9b2',
    messagingSenderId: '677074689591',
    projectId: 'fir-chat-app-4663a',
    storageBucket: 'fir-chat-app-4663a.appspot.com',
    iosBundleId: 'com.chatapp.firebaseChat.RunnerTests',
  );
}
